### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by boredland** [keonik/prisma-erd-generator#10]
Sadly for me (Arch Linux, nothing fancy), there is no output. For a test I did spin up a Github Workspaces instance with the latest commit. Running `npm run dev-test` here resulted in no new ERD.svg being generated.

**Comment by boredland** [comment]
I think its mainly incompatible with ... everything. Will try and check if I can update it a bit.

**Comment by keonik** [comment]
@davidecutrupi Can you test the `@next` version to verify it works on Windows and @boredland the same test with Linux?
