### ISSUE TITLE
Fails to find mmdc binary in Yarn 2 with Plug'n'Play

### ISSUE THREAD

**Issue by zkulbeda** [keonik/prisma-erd-generator#104]
[Example repo](https://github.com/zkulbeda/prisma-erd-generator-issue)
Error:
```
Error: Command failed: find ../.. -name mmdc
```
or another error:
```
Error: Expected mermaid CLI at
C:\Users\user\Project\prisma\node_modules\.bin\mmdc

or
undefined
 but this package was not found.
```

**Comment by keonik** [comment]
This is the most common problem we keep running into. `node_module` mapping to successfully call a CLI for Mermaid. Happy to review PR's related to a fix. It seems all that have been merged have fixed for one case and failed for the next. In the meantime, to generate in a format that will skip the CLI failure you could generate to markdown

```prisma
generator erd {
  provider = "prisma-erd-generator"
  output   = "./dist/erd.md"
}
```

I just tried it out and it generated successfully which tells me its not a formatting issue for the CLI, just a path issue

**Comment by zkulbeda** [comment]
It really worked! Thank you.

**Comment by Markkos89** [comment]
Hi @keonik , such a great generator, thanks and congrats.

Just for letting you know, running on a WSL2 ubuntu 22 distro, with the --data-proxy flag, the generator fails.. also added the output as you suggested here previously. The ouput is:

![image](https://user-images.githubusercontent.com/2791028/178977017-08457be1-a3d9-43e8-b652-d96924aa871b.png)

workaround to it by creating an **empty** `erd.md` file in the output path.

Best regards and thanks again!

**Comment by zkulbeda** [comment]
Hi @Markkos89, Github has build-in support for rendering [mermaid](https://github.com/mermaid-js/mermaid) language syntax. Just push `.md` file into github repo and check it out. On the other hand, you can render mermaid code manually on https://mermaid.live/edit

**Comment by keonik** [comment]
I believe all that is in the generated mermaid markdown file is something like this

```bash
"""mermaid
// syntax to render ERD in markdown
"""
```

So if you copied the contents out of that generated markdown file and into your README.md wherever you want to put it, it should render for you.

**Comment by keonik** [comment]
Added another option to specify the path to the binary for `mmdc` in #188

Although markdown is a workaround to generate successfully, this will let you find the path to the binary so that wherever it does exist it won't throw the package not found error anymore. Let me know if you run into issues
