### ISSUE TITLE
Table and column name mapping bug

### ISSUE THREAD

**Issue by francismanansala** [keonik/prisma-erd-generator#114]
Hi, I've encountered a weird bug with how I'm using mappings and `prisma-erd-generator`. Everything in Prisma generates the way I'd expect but `prisma-erd-generator` generates a svg for me with names I'm not expecting. Here's some example that recreates the issue:
`prisma.schema`:
```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "client"
}

generator erd {
  provider = "prisma-erd-generator"
  output = "./erd.svg"
  theme = "default"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Store {
  @@map("stores")

  id                String            @map("store_id") @id @default(uuid())

  employees         Employee[]
  customers         Customer[]
}

model Employee {
  @@map("employees")

  id                String            @map("employee_id") @id @default(uuid())
  storeId           String            @map("store_id")

  store             Store             @relation(fields: [storeId], references: [id])
  orders            Order[]
}

model Customer {
  @@map("customers")

  id                String            @map("customer_id") @id @default(uuid())
  storeId           String            @map("store_id")

  store             Store             @relation(fields: [storeId], references: [id])
  orders            Order[]
}

model Order {
  @@map("orders")

  id                String            @map("order_id") @id @default(uuid()) 
  employeeId        String            @map("employee_id")
  customerId        String            @map("customer_id")

  employee          Employee          @relation(fields: [employeeId], references: [id])
  customer          Customer          @relation(fields: [customerId], references: [id])
}

```

SVG generated by `prisma-erd-generator`:
![erd](https://user-images.githubusercontent.com/10519099/180878878-dddc7461-afd3-4795-abba-dc5254072e52.svg)

What I expecting to see in the SVG was: the PK for the orders table should be `order_id`, PK for the employees table should be `employee_id`, and PK for customers should be `customer_id`.

Am I doing something wrong?

**Comment by keonik** [comment]
You're not doing anything wrong. That's interesting. Without starting it up to troubleshoot I'm guessing its got something to with the placement of `@@map` as of now. Could you turn on debug mode and see what your mermaid generated file looks like?

**Comment by francismanansala** [comment]
> You're not doing anything wrong. That's interesting. Without starting it up to troubleshoot I'm guessing its got something to with the placement of @@map as of now. Could you turn on debug mode and see what your mermaid generated file looks like?

Here's the output from the debug mode

`prisma.mmd`
```mermaid
erDiagram

  stores {
    String store_id PK 
    }
  

  employees {
    String store_id PK 
    String store_id  
    }
  

  customers {
    String store_id PK 
    String store_id  
    }
  

  orders {
    String store_id PK 
    String employee_id  
    String customer_id  
    }
  
    employees o{--|| stores : "stores"
    customers o{--|| stores : "stores"
    orders o{--|| employees : "employees"
    orders o{--|| customers : "customers"

```

It looks pretty similar to the svg

**Comment by keonik** [comment]
I think I found it. Its related to the `mapPrismaToDb` function. The way `@map` and `@@map` are being read in are incorrect. Working on it

**Comment by keonik** [comment]
[mapToPrismaDB](https://github.com/keonik/prisma-erd-generator/blob/main/src/generate.ts#L294)

**Comment by keonik** [comment]
@francismanansala can you give v1.0.2 a test. I'm trying on my project now but I didn't have this issue before. Test case was written so I'm assuming this is safe to be closed

**Comment by francismanansala** [comment]
> @francismanansala can you give v1.0.2 a test. I'm trying on my project now but I didn't have this issue before. Test case was written so I'm assuming this is safe to be closed

Works perfectly within my test scenario and project 🚀 Thanks for the quick turn around on this @keonik!
