### ISSUE TITLE
Allow hiding ENUM tables

### ISSUE THREAD

**Issue by cjoecker** [keonik/prisma-erd-generator#120]
It would be nice to be able to hide enum tables with an extra flag in the schema.
When you have many enums, the diagram is not so easy to understand anymore.

**Comment by ripry** [comment]
Actually, I implemented hiding enums by mistake when making in table only mode, so we can use that implementation.
this commit -> [66d2d07](https://github.com/keonik/prisma-erd-generator/pull/90/commits/66d2d07be6234405bd2d4741c57daf866b88d702)
