### ISSUE TITLE
Make ERD diagram more user friendly

### ISSUE THREAD

**Issue by cjoecker** [keonik/prisma-erd-generator#121]
Right now the diagrams are looking good. Nevertheless, I think they would be easier to understand with the following changes:
![image](https://user-images.githubusercontent.com/46030630/183057517-89fc864a-f98e-4798-bf37-67bb723940d0.png)

What do you think?
I can try to make a PR for that if you like it

**Comment by keonik** [comment]
I would agree that’s easier to read. It could potentially save some space as well.  Yeah make a PR and I’ll review

**Comment by cjoecker** [comment]
I was checking `mermaid` and there are not too many possibilities for customizing.
But we can achieve that with [graphviz](https://graphviz.org/) and [handlebars](https://handlebarsjs.com/).
The logic may change but the end result will be the same. 

Here is a list of pros and cons of doing so:
1. We can customize the diagram using HTML and CSS preserving .svg as the output
2. At a later stage we can allow importing custom templates. That gives the user the possibility to style the diagram as they wish.
3. It would not be 100% UML conform. The relationships need to be done as it is done in [dbml diagrams](https://dbdiagram.io/home) (1,N on top of the lines next to the attributes). That is a pro for me as they are easier to read as UMLs.
4. It is not an out-of-the-box solution as a mermaid for ERD diagrams.
5. The default `mermaid` styles will not be there anymore (but they are not so nice anyway 😅)

What do you think? Would you be ok to switch the render engine?

**Comment by keonik** [comment]
I'm open to it. Especially if someone has an interest in sending a PR my way. There is a discussion about moving to something other than mermaid already #102

**Comment by keonik** [comment]
I did the best I could with mermaid's limitations. I couldn't put the key next to the string attribute or the type for some reason. What I did was combined the last column to show ❓ for nullable and 🗝️ for PK's

<img width="488" alt="Screenshot 2023-03-27 at 11 00 51 PM" src="https://user-images.githubusercontent.com/46365891/228116541-3cf6d1fe-d4d7-454c-8470-3061bef77ead.png">

[commit for reference](https://github.com/keonik/prisma-erd-generator/commit/dbd911776edf0992dd2879d20097ed2590037e8e)

**Comment by keonik** [comment]
@cjoecker We should keep the conversation going for dbml/graphviz alternatives. I can easily tack on a branch for a variant of this repository.
