### ISSUE TITLE
Prisma One-to-many Relationships Always Show as Required?

### ISSUE THREAD

**Issue by cmeyer-uncomn** [keonik/prisma-erd-generator#124]
macOS BigSur
node v17.2.0

Hi! It's very possible this question is not an actual issue with the ERD generator but rather caused by how Prisma handles relationships. However, I can't seem to find any clear information online about it.

To demonstrate, I'll use the example from the bottom of [Prisma's One-to-many documentation page](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#required-and-optional-relation-fields-in-one-to-many-relations). In this example the docs say: "you can create a Post without assigning a User". This is true, posts can be created without a user with no problems. However, the ERD generated shows that Post-to-User is a required relationship (image below). Is this an issue with the ERD generator? Or is there something I don't fully understand about One-to-many relationships in Prisma?

```prisma
model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id       Int   @id @default(autoincrement())
  author   User? @relation(fields: [authorId], references: [id])
  authorId Int?
}
```
<img width="652" alt="Screen Shot 2022-08-17 at 2 39 06 PM" src="https://user-images.githubusercontent.com/83987537/185228176-a9efd713-165f-40cf-8a5a-58d7fe2943f6.png">

**Comment by keonik** [comment]
Looking at mermaid docs on [relationships](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=relationship-syntax) you would expect to see
- User has zero to many Posts
- Post has zero to one User

Turning on debug mode I printed the generated output that feeds into mermaid

```bash
erDiagram

  User {
    Int id PK 
    }
  

  Post {
    Int id PK 
    }
  
    Post o{--|| User : "author"

```

I believe the last line there `    Post o{--|| User : "author"` should be

```bash
    Post o{--|o User : "author"
```

which would result in 

```mermaid
erDiagram

  User {
    Int id PK 
    }
  

  Post {
    Int id PK 
    }
  
    Post o{--|o User : "author"

```

**Comment by keonik** [comment]
I got it to this by changing a few lines that I haven't touched in many months 😳 

```mermaid
erDiagram

  User {
    Int id PK 
    }
  

  Post {
    Int id PK 
    }
  
    Post o{--|o User : "author"
```

**Comment by keonik** [comment]
Doesn't look right though. Its gonna take some more troubleshooting. I'll push up a branch shortly in case you would like to take a look

**Comment by keonik** [comment]
Take a look at that PR. Good catch on this bug ❤️
