### ISSUE TITLE
Support table names with special characters and spaces

### ISSUE THREAD

**Issue by michaelaltmann** [keonik/prisma-erd-generator#127]
Support table names like [Production$My Table]

**Comment by keonik** [comment]
Does mermaid support this format? They already throw errors with spaces in table names. I've expressed concern about doing that just because matching back to the Prisma schema has been important to many developers.

**Comment by keonik** [comment]
I did it! Wrapping whatever in double quotes `"[Production$My Table]"` made mermaid-js happy. I gotta assume this means most if not all characters but double quotes will be fair game.

<img width="364" alt="Screenshot 2023-03-27 at 11 07 02 PM" src="https://user-images.githubusercontent.com/46365891/228117407-619cf4a1-5b78-4911-bfbe-debfaff4bce6.png">

If you have more use cases than above please share.
