### ISSUE TITLE
Support mapped column names with special characters

### ISSUE THREAD

**Issue by michaelaltmann** [keonik/prisma-erd-generator#129]
For example
 amount                    Float?          @map("Amount (LCY)")

**Comment by keonik** [comment]
I believe this already works

```prisma
amount Float? @map("Amount (LCY)")
```

**Comment by keonik** [comment]
Wait nevermind. This is less a library limitation and more of a mermaid issue. I just tried fixing the regex used to get the strings. Even after getting it to parse out the right string it failed in the mermaid command.

**Comment by keonik** [comment]
Closing as this is a limit of mermaid
