### ISSUE TITLE
Using @map for FK field messes up the PK fields

### ISSUE THREAD

**Issue by balzafin** [keonik/prisma-erd-generator#138]
Code like this

```prisma
generator erd {
    provider = "prisma-erd-generator"
    output   = "./erd/ERD.md"
}

model User {
    id   Int    @id @default(autoincrement())
    name String

    userSettings UserSetting[]
}

model UserSetting {
    id     Int @id @default(autoincrement())
    userId Int @map("user_id")

    user User @relation(fields: [userId], references: [id])
}
```

generates this

```mermaid
erDiagram

  User {
    Int user_id PK 
    String name  
    }
  

  UserSetting {
    Int user_id PK 
    Int user_id  
    }
  
    UserSetting o{--|| User : "user_id"
```

If I remove the `@map("user_id")`, I get what I expect
```mermaid
erDiagram

  User {
    Int id PK 
    String name  
    }
  

  UserSetting {
    Int id PK 
    }
  
    UserSetting o{--|| User : "user"
```

Using
- @prisma/client@4.3.1
-  prisma-erd-generator@1.2.0

Seems to be similar to https://github.com/keonik/prisma-erd-generator/issues/114.

Hopefully this is simple enough example to reproduce the issue. Please let me know if you need additional information.

**Comment by keonik** [comment]
@all-contributors add @balzafin for bug

**Comment by keonik** [comment]
@dznbk @balzafin sent out a version with your MR for a fix for this. I believe I was running into this as well. I was going to check if this is resolved sometime next week. If you all beat me to it let me know if it's working for you. Thanks

**Comment by balzafin** [comment]
Can confirm that the the issue is now fixed 🎉  Thank you @dznbk and @keonik!
