### ISSUE TITLE
File change on each generate

### ISSUE THREAD

**Issue by hlehmann** [keonik/prisma-erd-generator#163]
SVG content use random ids, making a different result for each generate.

I would like to commit this file, but currently the file change even if the schema is the same.

Would it be possible to avoid this ? To prevent unchanged generation or to use incremental ids so the results are the same ?

**Comment by keonik** [comment]
I've been trying to figure out what changed that for a bit. Haven't come up successful yet.

**Comment by dee-me-tree-or-love** [comment]
Adding my two-pence here, I've also tried looking at it a little and it might be related to how `mermaid` is generating the SVG IDs: https://github.com/mermaid-js/mermaid/issues/1601 💭. Do you think this could be the reason?

**Comment by keonik** [comment]
Sounds exactly related. We do have `deterministidIds` set to true in our mermaid cli config. What that did before was set all unix timestamps to an ordinal id for example `mermaid-{unix timestamp}` to `mermaid-0` and it appears that still works but something in mermaid changed to persist a uuid to the id's further down the svg

**Comment by keonik** [comment]
After upgrading to v10 on the alpha release I am not getting the changes every time I run `prisma generate`. Give it a try and let me know if it's resolved for you all.

```bash
npm i -D prisma-erd-generator@alpha 
```
