### ISSUE TITLE
errro when i use npm prisma generate

### ISSUE THREAD

**Issue by lucasdesouza-dev** [keonik/prisma-erd-generator#164]
![image](https://user-images.githubusercontent.com/55006206/214728679-e4d48caf-473b-4437-be23-e736bf9fd5ee.png)

![image](https://user-images.githubusercontent.com/55006206/214728923-28cfcdfd-3a0a-4c75-bb79-d76d304a4b5f.png)

![image](https://user-images.githubusercontent.com/55006206/214728973-4af6298e-35e4-47fd-9db1-777896b23b82.png)

![image](https://user-images.githubusercontent.com/55006206/214729006-e6923d53-e76f-4c74-bd09-a50d7733a124.png)

![image](https://user-images.githubusercontent.com/55006206/214729079-a077e0a0-b9e9-4a82-a28e-9033f955f72c.png)

 does anyone help to resolve this error? if you've been through this

**Comment by keonik** [comment]
Have you tried commenting out some of the `@@map` usages to see if that can remove the error? What do your debug generated files look like?

**Comment by keonik** [comment]
Closing due to no response to help troubleshooting
