### ISSUE TITLE
Add a note about `@mermaid-js/mermaid-cli` dependency

### ISSUE THREAD

**Issue by maticzav** [keonik/prisma-erd-generator#178]
Thank you for this neat generator!

When I tried using it with Prisma 4.10.1 and pnpm, I was getting an error that `mmdc` command failed.

```sh
Command failed: ../../amsterdam/node_modules/mmdc -i /var/folders/lk/g24rtghs1gn_6l6tc9tcdnmm0000gn/T/prisma-erd-UdJgkH/prisma.mmd -o /Users/maticzavadlal/Code/mine/amsterdam/server/prisma/ERD.svg -t forest -c /var/folders/lk/g24rtghs1gn_6l6tc9tcdnmm0000gn/T/prisma-erd-UdJgkH/config.json
```

After looking into the problem, I was able to resolve it by adding an explicit dependency to `@mermaid-js/mermaid-cli`.

**Comment by keonik** [comment]
The installation step says to install this as a dev dependency already.
