### ISSUE TITLE
Many to many relationships not generated

### ISSUE THREAD

**Issue by LQR471814** [keonik/prisma-erd-generator#184]
Many to many relationships are not generated, this is a regression of https://github.com/keonik/prisma-erd-generator/pull/26.

```mermaid
erDiagram

  Booking {
    Int id PK 
    }
  

  Event {
    Int id PK 
    String name  
    DateTime startDate  
    }
```

- OS: Ubuntu 22.10
- Node: v19.6.1
- Output related to error: https://github.com/LQR471814/prisma-erd-missing-many
- Explanation of steps to get error:
  - Set up Prisma ORM and `prisma-erd-generator`.
  - Insert example from https://github.com/keonik/prisma-erd-generator/pull/26.
  - `prisma generate`

**Comment by keonik** [comment]
I may tackle this as part of upgrading mermaid. I had thought it was only related to the upgrade but if its still happening on v8 mermaid I'll take a look. Thank you for bringing this up

**Comment by keonik** [comment]
@LQR471814 I may have fixed this. It required deleting [this line](https://github.com/keonik/prisma-erd-generator/pull/175/files#diff-0e9ffa40772b7eca15b8e9fed0a847258c6a80dca2f41d5ddc0cb70357736f2cR240).

**Comment by keonik** [comment]
I'm not sure why the to/from relations fields changed. Removing that line didn't cause any other tests to fail but as with a change like this it almost always has some downstream affects

**Comment by keonik** [comment]
Closing as its resolved for tests and my projects. Let me know if you still have issues.
