### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by janpio** [keonik/prisma-erd-generator#2]
After fixing https://github.com/keonik/prisma-erd-generator/issues/1 manually, I still did not get a svg file. I could pinpoint it to https://github.com/keonik/prisma-erd-generator/blob/f5afa685e254494341c979c5e1ec9f608b709c3e/src/generate.ts#L167-L174 which does not work on Windows.

A bit of hacking in `generate.js` did not help, so I uncommented the line that deletes the temp file afterwards, and ran the following command manually: `npx mmdc -i prisma/input.mmd -o C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\prisma\\ERD.svg -t forest`. 

Maybe that can be turned into a cross platform solution to this problem.

**Comment by keonik** [comment]
Without digging into it, my guess is the file path I'm using isn't mapping to windows correctly. I built it only considering mac/linux. I can take this one. @janpio If you have some bandwidth I might need help validating it fixed the issue.

**Comment by janpio** [comment]
Yep, on Windows you can probably generally not just execute a path starting with `.` and with the path, but need to supply the `cwd`. Even then I am not sure if running the file in `.bin` is the right approach here in general - I do not have the experience with this to evaluate. I knew that using `npx` in the project root would work - but not sure if that is the correct approach here either. Maybe mmdc has a programmatic API... that should be cross platform most probably.

**Comment by keonik** [comment]
@janpio I've got a PR up for this but I went ahead and pushed to `next` on npm. Could you see if that works for you?

**Comment by janpio** [comment]
Hmmm, something weird is going on.

If I just run that version under `@next` nothing happens (Even when I fix #1 manually again).
But if I output the generated command with `console.log(mermaidCliNodePath, '-i', inputMermaidFile, '-o', output, '-t', theme)` and run that manually (`C:\Users\Jan\Documents\throwaway\repro8264\node_modules\.bin\mmdc -i C:\Users\Jan\Documents\throwaway\repro8264\prisma\input.mmd -o C:\Users\Jan\Documents\throwaway\repro8264\prisma\ERD.svg -t forest`), it works and created the file in the correct location!?

If I `var spawn = child_process...` and then output `spawn` I see this:
```
{
  error: Error: spawnSync C:\Users\Jan\Documents\throwaway\repro8264\node_modules\.bin\mmdc ENOENT
      at Object.spawnSync (internal/child_process.js:1067:20)
      at Object.spawnSync (child_process.js:602:24)
      at Object.exports.default [as onGenerate] (C:\Users\Jan\Documents\throwaway\repro8264\node_modules\prisma-erd-generator\dist\generate.js:128:35)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\repro8264\node_modules\@prisma\generator-helper\dist\generatorHandler.js:13:32) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawnSync C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\node_modules\\.bin\\mmdc',
    path: 'C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\node_modules\\.bin\\mmdc',
    spawnargs: [
      '-i',
      'C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\prisma\\input.mmd',
      '-o',
      'C:\\Users\\Jan\\Documents\\throwaway\\repro8264\\prisma\\ERD.svg',
      '-t',
      'forest'
    ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

Which does not make much sense as that is the exactly the path from above. Weird.

**Comment by keonik** [comment]
@janpio my next attempt will be to move away from the CLI and see if we can use the Mermaid API. I'm going to merge in what we've got because it's at least a step in the right direction.

**Comment by keonik** [comment]
@janpio Can you validate `@next` version is working for you on Windows? Issue #9 also has someone testing on Windows so hopefully one of you two can test it and get this closed

**Comment by janpio** [comment]
Seems I am to late to test this, but I can confirm `0.4.0` creates a valid .svg file on Windows 👍
