### ISSUE TITLE
Problem using pnpm

### ISSUE THREAD

**Issue by benquan** [keonik/prisma-erd-generator#203]
When using NPM I have no issues, `npm prisma generate` runs and generates the desired ERP daigram.

my code in schema.prisma is:
```
generator erd {
  provider = "prisma-erd-generator"
  output   = "../static//ERD.svg"
}
```

I reinstall everyting using pnpm and run `pnpx prima generate`, I get the following error:
```
Error: Generator at prisma-erd-generator could not start:

/bin/sh: prisma-erd-generator: command not found

 ERROR  Command failed with exit code 1: prisma generate

pnpm: Command failed with exit code 1: prisma generate
    at makeError (/Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:24159:17)
    at handlePromise (/Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:24730:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:220504:7)
    at async /Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:228244:21
    at async main (/Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:228211:34)
    at async runPnpm (/Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:228466:5)
    at async /Users/ben/.cache/node/corepack/pnpm/7.30.0/dist/pnpm.cjs:228458:7
```

**Comment by keonik** [comment]
> `pnpx prisma generate` gives us the same error, but `pnpm prisma generate` works.

That makes sense. Because pnpx isn’t going to fetch all your generator dependencies as well. So it may be running from a different folder than the pnpm install which means that .bin/mmdc program might not exist where it is looking.

**Comment by TeePlunder** [comment]
I'm currently trying to generate my erd in an actions pipeline. On my machine it works fine with pnpm but in the action I get the following error:
```
Command failed: /home/runner/work/ProTrack-2023/ProTrack-2023/node_modules/.bin/mmdc -i /tmp/prisma-erd-n2bzkt/prisma.mmd -o /home/runner/work/ProTrack-2023/ProTrack-2023/prisma/erd/erd.svg -t forest -c /tmp/prisma-erd-n2bzkt/config.json
```

my generator config looks like this
```
generator erd {
  provider                  = "prisma-erd-generator"
  output                    = "./erd/erd.svg"
  theme                     = "forest"
  includeRelationFromFields = true
  mmdcPath                  = "node_modules/.bin"
}
```

**Comment by keonik** [comment]
Everything looks good to me. Does generating a markdown work? If so, its related to where github actions or gitlab is putting those `.bin` files

**Comment by TeePlunder** [comment]
Yes that works. I will look up where github is putting the `.bin`

**Comment by benquan** [comment]
> `pnpx prisma generate` gives us the same error, but `pnpm prisma generate` works.

This was the solution, closing the issue.
