### ISSUE TITLE
Having the theme in a env var cause errors

### ISSUE THREAD

**Issue by oxypomme** [keonik/prisma-erd-generator#208]
Hi !

First of all, thanks for this really good tool!

I have an issue where 

```prisma
generator erd {
  provider = "prisma-erd-generator"
  output = env("ERD_OUT")
  theme = env("ERD_THEME")
}
```

with following env :

```console
$ env | grep ERD
ERD_OUT=../ERD.png
ERD_THEME=forest
```

fails with error :
```
Error: 
Command failed: /home/pptruser/node_modules/.bin/mmdc -i /tmp/prisma-erd-XhKIv7/prisma.mmd -o /home/pptruser/ERD.png -t (function) -c /tmp/prisma-erd-XhKIv7/config.json
```

If I change the theme into `prisma.schema`, it works well tho.

**Comment by keonik** [comment]
I ran into this myself. I'll need to discuss this with prisma to see how they are doing it.

**Comment by keonik** [comment]
The fix for this is published on the alpha release. You would need to create a [mermaid config file](https://github.com/keonik/prisma-erd-generator/tree/alpha#mermaid-configuration) and set your theme based on the env value passed in. I plan to publish this to the next release
