### ISSUE TITLE
@prisma/generator-helper seems to be required to run the generator

### ISSUE THREAD

**Issue by Bernold1** [keonik/prisma-erd-generator#210]
After installing the prisma-erd-generator to my yarn workspace and adding the generator to my `schema.prisma` file, running the generator throws the error: 
`Error: Cannot find module '@prisma/generator-helper'`
When reviewing the package description on npmjs, it clearly states that the package is intended for Prisma's internal use. 
Is there a workaround for this without adding the package to my application/workspace, or is this simply a bug?

**Comment by keonik** [comment]
We are using that module in the generator. It has types for the options used in [generate.ts](https://github.com/keonik/prisma-erd-generator/blob/5618b7d9d305ac45380a4260b22e54eda9b9f04c/src/generate.ts#L363) and it is installed as a needed [peer dependency](https://github.com/keonik/prisma-erd-generator/blob/5618b7d9d305ac45380a4260b22e54eda9b9f04c/package.json#L70).

**Comment by keonik** [comment]
fair enough. I'll move it over as a dependency. I'm seeing others do the same
