### ISSUE TITLE
Allow to select tables due tables visibility

### ISSUE THREAD

**Issue by yangricardo** [keonik/prisma-erd-generator#215]
Would be nice to generate the ERD from selected tables.
In database that contains a large quantity of tables, or relations, it has a poor view that only svg format enables to zoom to the tables content and on browser may be not sufficient

**Comment by keonik** [comment]
Would this be similar https://github.com/keonik/prisma-erd-generator/issues/82?

**Comment by keonik** [comment]
Duplicate issue https://github.com/keonik/prisma-erd-generator/issues/82
