### ISSUE TITLE
git tags cause semantic-release to fail

### ISSUE THREAD

**Issue by schiller-manuel** [keonik/prisma-erd-generator#224]
The git tags v1.7.0 and v1.8.0 point to commits (8a267347c7f7d319fcf5779261ce17a9187ac751 and afeaf80fd8d719a472d8d3f6c36f53fd7ed45f81) that are neither part of branch `main` nor `alpha`.
Tag v1.6.0 points to 6f6929fb568ec34f4074f9cabde557b8cea0b1a1 which is is on both branches, hence `semantic-release` thinks the next version will be v1.7.0.

maybe the git history was rewritten?
a fix for this issue could be to delete the v1.8.0 tag and create a new tag that points to a commit that is on both branches, e.g. 217142fecee2dc4837e7666a48bef1378eff4529

**Comment by keonik** [comment]
yeah. 😢 The alpha/beta release side of this semantic-release setup haven't worked for me yet. I haven't been checking this out nearly enough lately. I will do what you suggested and delete the 1.8.0 tag

**Comment by keonik** [comment]
Still haven't figured out why its failing but I have a workaround that seems to be successful the past few weeks. Alpha releases are pretty seamless and github actions seem to be doing what they were supposed to do. With main, I just need to manually trigger a release the way I used to do it.
