### ISSUE TITLE
ERD not generated when DISABLE_ERD=false is set in .env file

### ISSUE THREAD

**Issue by mipicdev** [keonik/prisma-erd-generator#225]
**Issue Type:** 

Bug

**Description:**

When I set `DISABLE_ERD=false` in my `.env` file, no ERD is generated, which is contrary to the expected behavior. When I remove this variable, the ERD generation works again as expected.

**Environment:**

- OS: Ubunutu
- Node.js version: 18.16.1
- Prisma version: 4.14.0
- prisma-erd-generator version: 1.8.0

**Steps to reproduce:**

1. Add `DISABLE_ERD=false` to the `.env` file.
2. Run the ERD generation process.

**Expected behavior:**

When `DISABLE_ERD=false` is set in the `.env` file, the ERD should be generated.

**Actual behavior:**

No ERD is generated when `DISABLE_ERD=false` is set.

**Relevant code:**

`.env` file:
```
DATABASE_URL="file:./dev.db"
DISABLE_ERD=false
```

`schema.prisma` file:
```
generator erd {
  provider = "prisma-erd-generator"
  output   = "../prisma/erd.png"
}
```

**Comment by shiralwz** [comment]
I think this PR might fix the issue https://github.com/keonik/prisma-erd-generator/pull/227
