### ISSUE TITLE
Error: could not parse datamodel

### ISSUE THREAD

**Issue by janpio** [keonik/prisma-erd-generator#24]
I have a recent schema (39 models) created via `db pull` with `3.4.2`. Unfortunately no svg is created and with `DEBUG=*` I see this error message:

```
  prisma:GeneratorProcess Error: could not parse datamodel +463ms
  prisma:GeneratorProcess     at Object.exports.default [as onGenerate] (C:\Users\Jan\Documents\throwaway\cloud-api\node_modules\prisma-erd-generator\dist\generate.js:146:19) +1ms
  prisma:GeneratorProcess     at processTicksAndRejections (internal/process/task_queues.js:95:5) +0ms
  prisma:GeneratorProcess     at async LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\cloud-api\node_modules\@prisma\generator-helper\dist\generatorHandler.js:36:24) +1ms
```

What is the best way to debug this?

(I unfortunately can not share the schema here)

**Comment by janpio** [comment]
Seem the base64 was too big for the Prisma Query Engine CLI and the param `--datamodel`, but writing the plain model to a file (could also have used the path instead probably) and using `--datasource-path` worked and I got a SVG 👍

**Comment by keonik** [comment]
@janpio It might be related to #16.

**Comment by keonik** [comment]
@janpio Did you say you fixed this above or was an upgrade to the latest version enough of a fix. The write to temp file was in the latest version last I checked so it should solve the base64 issue.

**Comment by janpio** [comment]
I installed from Npm, so am/was using `"prisma-erd-generator": "^0.5.3"`. But what I see at https://github.com/keonik/prisma-erd-generator/pull/17/files looks exactly what I did manually as well. Could it be that `0.5.3` somehow does not include these changes?

**Comment by keonik** [comment]
I'm gonna see if its included in the `0.6.0` release with the m:n

**Comment by keonik** [comment]
<img width="668" alt="Screen Shot 2021-11-15 at 10 48 28 AM" src="https://user-images.githubusercontent.com/46365891/141811713-0c0fdfd2-3a6f-4d86-bc98-f4d88c585c4b.png">

I'm seeing usage of the `--datamodel-path` in v0.6.0. Assuming that's a similar fix I think we can close this @janpio

**Comment by janpio** [comment]
Agree 👍

**Comment by Nypeeh** [comment]
I had the same problem. "Error: could not parse datamodel".
I solved that with a simple solution above.

My directory to the folder project was:

```diff
- D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
```

Pay attention that "Projetos Gerais" has a blank space

My solution was replace that space to "_".

```diff
- Projetos Gerais
+ Projetos_Gerais
```

### Fixed directory
```diff
+ D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
```

After that, the error was solved for me. I hope this can help someone.

**Comment by brunotravassos93** [comment]
> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

Boa, irmão. Resolveu aqui!!

**Comment by jancyaragao** [comment]
> Referen

Thanks, that helped me

**Comment by jancyaragao** [comment]
https://github.com/keonik/prisma-erd-generator/issues/24#issuecomment-1107362004

Thanks, that helped me

**Comment by jancyaragao** [comment]
> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

Thanks, that helped me

**Comment by lucascavalcante25** [comment]
Resolvido aqui também, removendo apenas o espaço!
Vocês são feras!!

**Comment by FeAranha** [comment]
I'm on linux and I create the project without space but with a capital letter, does it interfere? 
```
λ notefe server → pwd                                                  
/home/fearanha/devs/nlwCopa/server
```

**Comment by matteothebrave** [comment]
i had the same issue and solved with 

> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

I had the same issue and your tip solved my problem. 
I really appreciate

**Comment by rodrigogeraldes** [comment]
> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

This solved my problem! Thank you

**Comment by ivanbs14** [comment]
> > Eu tive o mesmo problema. "Erro: não foi possível analisar o modelo de dados". Eu resolvi isso com uma solução simples acima.
> > Meu diretório para o projeto da pasta era:
> > ```diff
> > - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Preste atenção que "Projetos Gerais" tem um espaço em branco
> > Minha solução foi substituir esse espaço por "_".
> > ```diff
> > - Projetos Gerais
> > + Projetos_Gerais
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Diretório fixo
> > ```diff
> > + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Depois disso, o erro foi resolvido para mim. Espero que isso possa ajudar alguém.
> 
> Boa, irmão. Resolveu aqui!!

>Parabéns, deu certo. (era uma pasta do meu diretório que tinha espaço).

**Comment by CaioSouzaC1** [comment]
Resolvido também retirando os espaços!
Muito obrigado.

**Comment by augustoandreotti** [comment]
> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

Realmente era isso! Smp deixo as pastas sem nenhum espaço, mas deixei escapar um kkkk valeu!!

**Comment by kkphoenixgx** [comment]
I am coding into a google drive env, so the path is "C:\Users\kkpho\My Drive\Workdrive\..." and I just can not change "My drive". I will try to download it and run it in

**Comment by camilobreia** [comment]
> > I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> > My directory to the folder project was:
> > ```diff
> > - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Pay attention that "Projetos Gerais" has a blank space
> > My solution was replace that space to "_".
> > ```diff
> > - Projetos Gerais
> > + Projetos_Gerais
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Fixed directory
> > ```diff
> > + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, the error was solved for me. I hope this can help someone.
> 
> Thanks, that helped me


=> thanks bro, solve the issue

**Comment by Feurrado** [comment]
> 

Almost one year later, saving my project!

Thanks for the tip.

**Comment by Feurrado** [comment]
> I had the same problem. "Error: could not parse datamodel". I solved that with a simple solution above.
> 
> My directory to the folder project was:
> 
> ```diff
> - D:\\Projetos\\Projetos Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> Pay attention that "Projetos Gerais" has a blank space
> 
> My solution was replace that space to "_".
> 
> ```diff
> - Projetos Gerais
> + Projetos_Gerais
> ```
> 
> ### Fixed directory
> 
> ```diff
> + D:\\Projetos\\Projetos_Gerais\\fullcycle-prisma\\node_modules\\prisma\\query-engine-windows.exe
> ```
> 
> After that, the error was solved for me. I hope this can help someone.

> 

Almost one year later, saving my project!

Thanks for the tip.

**Comment by Feurrado** [comment]
> I am coding into a google drive env, so the path is "C:\Users\kkpho\My Drive\Workdrive..." and I just can not change "My drive". I will try to download and run my project in another env but it is really annoying.. No one have an other solution?

My project was uploaded to a OneDrive folder synched with my desktop, giving me the same error.

Moved to HD and problem solved.

**Comment by nilsonsierota** [comment]
The change of the spaces from folders work for me too, thanks! :)
