### ISSUE TITLE
No m:n relations rendered

### ISSUE THREAD

**Issue by janpio** [keonik/prisma-erd-generator#25]
I have a Prisma Schema that is based on a Prisma 1 schema, and only has m:n relations. Is it intentional that m:n relations are not rendered at all?

**Comment by keonik** [comment]
Definitely not. I just realized that as well.

**Comment by keonik** [comment]
It looks like there isn't a specific many-to-many relationship callout https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram but the zero to many is probably what we need. I'm gonna see if the temp mermaid file is generating it correctly

**Comment by keonik** [comment]
@janpio I'm not sure what the final version should look like for the m:n relationships but I do want to get something out there drawing the connections now and changes can be made.

**Comment by janpio** [comment]
Awesome - will test this out then!

**Comment by janpio** [comment]
Yep, that definitely did something: 
![image](https://user-images.githubusercontent.com/183673/141750988-59e289eb-472c-4048-b794-f93d7c34cc17.png)

Nice!

**Comment by keonik** [comment]
@janpio Do you think that's acceptable having two lines drawn and separate relationship names? I just took the easiest solution to push out something. I tried to adjust to having one line with the m:n relationship drawn but the relationship name added some confusion there.

**Comment by janpio** [comment]
This is definitely better than not having any lines - so there's that 😆 

The two lines on the other hand are indeed pretty confusing. It is a shame there is no better representation.

The schema I showed above does technically not even have m:n relations mostly, but is based on the SQL of a a Prisma 1 schema that unfortunately does not encode the information what kind of relation we are looking at. That is the reason why _all_ relations here look like m:n although they most probably are not really.

**Comment by keonik** [comment]
I can try to make a single line for the relationship added in there but it seems every time I try it it doesn't start with the proper many relationships. For now, my goal will be to just get the m:n down to one line and see if I can get it closer. We're at the limitation of mermaid in this instance though. 

Unrelated I have been debating making a generator without mermaid. Its on my backlog 😅
