### ISSUE TITLE
Unable to create svg file

### ISSUE THREAD

**Issue by mshige1979** [keonik/prisma-erd-generator#27]
schema.prisma
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

// ER図作成用
generator erd {
  provider = "prisma-erd-generator"
  output   = "../doc/ERD.svg"
  theme    = "forest"
}

// ユーザーデータ管理用
model User {
  // ID
  id    Int     @id @default(autoincrement())
  // メールアドレス
  email String  @unique
  // 氏名
  name  String?
  // 年齢
  age   Int?

  // 登録日時
  createdAt DateTime @default(now()) @map("created_at")
  // 更新日時
  updatedAt DateTime @default(now()) @map("updated_at")

  // プロフィール(One to One)
  profile Profile?
  // 記事(One to Many)
  posts   Post[]

  // テーブルの物理名
  @@map("users")
}

// プロフィール管理用
model Profile {
  // ID
  id       Int    @id @default(autoincrement())
  // ニックネーム
  nickName String @map("nick_name")

  // 登録日時
  createdAt DateTime @default(now()) @map("created_at")
  // 更新日時
  updatedAt DateTime @default(now()) @map("updated_at")

  // 親テーブルの関連づけ
  userId Int  @unique
  user   User @relation(fields: [userId], references: [id])

  // テーブルの物理名
  @@map("profile")
}

// 記事管理用
model Post {
  // ID
  id    Int    @id @default(autoincrement())
  // タイトル
  title String @map("title")

  // 登録日時
  createdAt DateTime @default(now()) @map("created_at")
  // 更新日時
  updatedAt DateTime @default(now()) @map("updated_at")

  // 親テーブルの関連づけ
  author   User @relation(fields: [authorId], references: [id])
  authorId Int

  // テーブルの物理名
  @@map("posts")
}

```

### generate
```
npx prisma generate
```

### result
```
prisma.mmd
```

What should i do?

**Comment by keonik** [comment]
The `prisma.mmd` is a temporary file I was using to test an unrelated issue. I forgot to remove that. I will add that in `0.6.1` to remove that file again. As for not generating though... I tried the output and usage and it worked for me assuming the directory already exists you're writing to. Which means its something in your schema. I will try it out when I get some more time.

**Comment by dvnrsn** [comment]
Cool idea. Experiencing the same (just an outputted mmd), no ERD 😢

**Comment by keonik** [comment]
@dvnrsn If you can post your prisma.schema and OS. I believe we've solved the OS specific problems and are down to schema specifics but it would be nice to have still

**Comment by keonik** [comment]
@mshige1979 and @dvnrsn can you try and install the newest version and see if this is still the case? 

```bash
npm i -D prisma-erd-generator@latest
```

**Comment by keonik** [comment]
@mshige1979 I ran your shared schema and got an SVG on version `0.6.1`
<img width="399" alt="Screen Shot 2021-11-23 at 7 26 55 PM" src="https://user-images.githubusercontent.com/46365891/143149536-ecb95d41-2fcc-4684-b3ea-e33df0b117c5.png">
