### ISSUE TITLE
No output generated

### ISSUE THREAD

**Issue by jasonmacdonald** [keonik/prisma-erd-generator#36]
I've looked through all the other topical issues and it seems even with the latest version I still cannot get it to produce any output, despite saying it completed just fine :( 

OS: MacOS 12.0.1
package version: 0.6.1

Schema
```

generator client {
  provider = "prisma-client-js"
}

generator erd {
  provider = "prisma-erd-generator"
  output   = "ERD.png"
}

generator nestgraphql {
  provider               = "node ../../../node_modules/prisma-nestjs-graphql"
  output                 = "../src/@generated/"
  reExport               = Single
  fields_Validator_from  = "class-validator"
  fields_Validator_input = true
}

datasource db {
  provider = "postgresql"
  url   = env("DATABASE_URL")
}

model User {
  /// @validator.IsUUID(all)
  id        String   @id @default(uuid()) @db.Uuid
  /// @Validator.IsEmail()
  email     String   @unique
  /// @Validator.Length(8, 64)
  password  String
  /// @Validator.IsJSON()
  roles     Json[]
  profile   Profile?
  /// @HideField({ output: false, input: true })
  createdAt DateTime @default(now())
  /// @HideField({ output: false, input: true })
  updatedAt DateTime @default(now())
}

model Profile {
  id        String @id @default(uuid()) @db.Uuid
  user      User   @relation(fields: [userId], references: [id])
  userId    String @unique @db.Uuid
  firstName String
  lastName  String
}

```

Console log says everything is fine

```
✔ Generated Entity-relationship-diagram to ./prisma/ERD.png in 621ms
```

But no diagram is produced.

**Comment by jasonmacdonald** [comment]
It appears it's looking for the mmdc file in the wrong place.

_NOTE: I removed some of the path and replaced them with `${PROJECT_ROOT}`. This is just the path to my project root.

```
'Command failed: /Users/${PROJECT_ROOT}/libs/api/model/node_modules/.bin/mmdc -i /var/folders/t6/4vwlff9j6r5frxsm0s5sdjmh0000gq/T/prisma-erd-4wfTkY/prisma.mmd -o /Users/${PROJECT_ROOT}/libs/api/model/prisma/ERD.png -t forest -c /var/folders/t6/4vwlff9j6r5frxsm0s5sdjmh0000gq/T/prisma-erd-4wfTkY/config.json'
```
 It should be looking here
```
/Users/${PROJECT_ROOT}/node_modules/.bin/mmdc -i 
```
but instead it's trying to find it inside my NX/libs folder

**Comment by keonik** [comment]
Hey Jason! I'm out on some paternity leave so I will get to this when I have some more time. I'm seeing a lot of others running into similar problems and I think its a project setup issue. I started this off of the base case of 

```bash
project/
   prisma/
      schema.prisma
```

and running the project from the project dir.

It works for that but there are some use cases I'm not thinking of. Is your situation any different from this?

For the time being I'm adding your schema to the test list to see if its an actual issue with the schema parsing or path or whatever else it could be. 

![36](https://user-images.githubusercontent.com/46365891/144780145-d863d2c0-74e4-4081-a174-f2a75b92bdc5.png)

**Comment by kefniark** [comment]
Same issue there
```
✔ Generated Entity-relationship-diagram to .\prisma\prisma-schema.svg in 106ms
```
But no file to be found anywhere

* Node 16
* Windows 10
* `prisma@3.6.x`
* `prisma-erd-generator@0.6.1`

**Comment by keonik** [comment]
I'm gonna add mermaid cli as a peer dependency that way it at least warns to install it as a dev dependency. It should already be included though as its a dependency for the package.

**Comment by keonik** [comment]
`0.7.0` is going to hopefully throw some errors if the mmdc library is missing or if the file isn't generated. It won't fix the no output generated but it hopefully will throw errors and get people to share whether they're getting the mmdc path correct or the cli command is failling.

**Comment by keonik** [comment]
@jasonmacdonald @kefniark Could one of you try out the next version and see if it at least throws errors for you?

**Comment by kefniark** [comment]
I confirm, now it throw an error if mermaid-cli is not available locally 👍 
```bash
Error: 
✔ Generated Prisma Client (3.6.0 | library) to .\node_modules\@prisma\client in 348ms

Error: Expected mermaid CLI at C:\Users\{PROJECT_PATH}\node_modules\.bin\mmdc but this package was not found.
```

**Comment by keonik** [comment]
Yeah easiest way forward there is to make the directory you want to output to. I'm closing now that this will give better insight into where the issues are coming up.
