### ISSUE TITLE
Dist Folder Issue

### ISSUE THREAD

**Issue by kefniark** [keonik/prisma-erd-generator#37]
## Description
Looking for debugging this library, noticed something strange. The dist folder contains different outputs and duplicates files.

```
dist/generate.js 180 lines
dist/src/generate.js 159 lines
```

Looks like something was caused by a tsconfig change at some point.

![image](https://user-images.githubusercontent.com/4903529/144964527-a7894448-6384-4e6f-89fd-392d8ea54c07.png)

Improvement ideas:
* Clean dist folder before running build
* Exclude src folder in .npmignore

**Comment by keonik** [comment]
Good suggestions. The cleanup for the dist folder was already happening but I'll add it as a prebuild step. I have no idea why the src directory is included.
