### ISSUE TITLE
Works locally but not when generated inside Dockerfile (node:15)

### ISSUE THREAD

**Issue by TMInnovations** [keonik/prisma-erd-generator#53]
Error:
```
#14 0.689 > npx prisma generate
#14 0.689
#14 2.049 Prisma schema loaded from prisma/schema.prisma
#14 16.61 Error:
#14 16.61 Error: Command failed: /app/node_modules/.bin/mmdc -i /tmp/prisma-erd-iGMeMD/prisma.mmd -o /app/prisma/ERD.pdf -t forest -c /tmp/prisma-erd-iGMeMD/config.json
#14 16.61     at checkExecSyncError (node:child_process:707:11)
#14 16.61     at Object.execSync (node:child_process:744:15)
#14 16.61     at Object.exports.default [as onGenerate] (/app/node_modules/prisma-erd-generator/dist/generate.js:187:23)
#14 16.61     at processTicksAndRejections (node:internal/process/task_queues:94:5)
#14 16.61     at async LineStream.<anonymous> (/app/node_modules/prisma-erd-generator/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
#14 16.61
#14 16.61
#14 16.61 ✔ Generated Prisma JSON Schema Generator to ./prisma/generated in 
38ms
#14 16.61
#14 16.61 ✔ Generated DBML Schema to ./prisma/generated in 40ms
#14 16.61
#14 16.61 ✔ Generated Prisma Docs Generator to ./prisma/generated/database-docs in 116ms
#14 16.61
#14 16.61 ✔ Generated Prisma Client (2.27.0) to ./node_modules/@prisma/client in 573ms
#14 16.61
#14 16.61 ✔ Generated Prisma NestJS/GraphQL to ./node_modules/@prisma/client/nestjs-graphql in 11.67s
#14 16.61
------
executor failed running [/bin/sh -c npm run prebuild]: exit code: 1
```

Version:
`"prisma-erd-generator": "^0.8.1"`

Generator Part inside schema.prisma:
```
...
generator erd {
  provider = "prisma-erd-generator"
  output   = "./ERD.pdf"
}
...
```

Dockerfile:
```
FROM node:15-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY ./src/ ./src/
COPY ./prisma/ ./prisma/
RUN npm ci --quiet
RUN npx prisma generate # <= failing line
```

**Comment by keonik** [comment]
I can replicate. The last version to work with docker was 0.6.1. I need to dig through the commits to see what happened in 0.7.0 to see if there is a way to make everyone’s use case work.

**Comment by justindasilva** [comment]
I am seeing the same issue as well:
```
#9 0.721 $ /usr/src/app/node_modules/.bin/prisma generate                                                                                          
#9 2.428 Environment variables loaded from .env                                                                                                    
#9 2.437 Prisma schema loaded from prisma/schema.prisma
#9 7.445 Error: 
#9 7.445 ✔ Generated Prisma Client (3.9.0 | library) to ./node_modules/@prisma/client in 528ms
#9 7.445 
#9 7.445 Error: Command failed: /usr/src/app/node_modules/.bin/mmdc -i /tmp/prisma-erd-skjR3u/prisma.mmd -o /usr/src/app/prisma/schema.svg -t forest -c /tmp/prisma-erd-skjR3u/config.json
#9 7.445     at checkExecSyncError (node:child_process:826:11)
#9 7.445     at Object.execSync (node:child_process:900:15)
#9 7.445     at Object.exports.default [as onGenerate] (/usr/src/app/node_modules/prisma-erd-generator/dist/generate.js:187:23)
#9 7.445     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#9 7.445     at async LineStream.<anonymous> (/usr/src/app/node_modules/@prisma/generator-helper/dist/generatorHandler.js:36:24)
#9 7.445 
#9 7.445 
#9 7.494 error Command failed with exit code 1.
```

By the way, is there a way to only have erd diagrams generate when in a dev environment?

I really only see a need to run the erd generator if a change is detected in the `schema.prisma` file.

**Comment by justindasilva** [comment]
I don't know if this is related, but at my workplace, when I started using `prisma-erd-generator`, I actually got a warning popup on my machine that the Cortex XDR (malware scanner) suspected malicious activity in application name: `query-engine-darwin`

I can use Prisma to generate all my models, but it is only after adding:
```
generator erd {
  provider = "prisma-erd-generator"
  output   = "../prisma/schema.svg"
}
```
to my `schema.prisma` file, that I see this error popup. (And the popup goes away when I comment this code out.)

I had to get my workplace to make an exception for me so that I can run the ERD Generator.
The exception they made has something to do with the path to my application, because when I changed some of my application structure recently, the warning popup started showing up. (The DevOp team had to alter the exception rule to take into account the change in path of my application.)

So I have a small hunch that because when I run my application through Docker, since it is a different path, that is why Docker is complaining, because the Malicious code scanner is interrupting the process.

**Comment by keonik** [comment]
Oh, that's interesting @justindasilva. I haven't had the time to figure out which version specifically started failing in docker. For my usage, I have been using an older version when I need to use docker. I like the idea of having it as an option to bypass. I tried the environment variable directly and it doesn't appear to be working in this PR https://github.com/keonik/prisma-erd-generator/pull/51

Short term work-around for now
- back up to use version `0.6.1`

**Comment by keonik** [comment]
I tested in the latest version `0.9.1` and it seemed to work for me again. Closing as I didn't see the issue after the latest upgrade.

**Comment by keonik** [comment]
Spoke too soon 😢

**Comment by keonik** [comment]
For now, the easiest route for my projects is the add-in a `DISABLE_ERD=true` to my environment variables when needed.

**Comment by TMInnovations** [comment]
Sorry to have to reopen this. 

Am I right? => In `0.9.1` it's still not possible to generate the erd inside a docker build. So this issue is not resolved, is it? If you don't want to address this issue I can also try to contribute if you tell me where to start. :-) 

All the best, 
Thomas

**Comment by keonik** [comment]
I think the consensus is to use the generate outside of docker and disable it in docker. It is not resolved to work in docker yet. When I saw it working in version `0.6.1` I tried to see anything that pointed out the diff in code between that and `0.7.0` and didn't see the easy fix I was looking for. If you wanted to work on it I would start with those versions and see what has changed
