### ISSUE TITLE
Not working for MongoDB

### ISSUE THREAD

**Issue by aladinflux** [keonik/prisma-erd-generator#62]
When using mongodb, the erd doesn't create any relationships. Is it possible to use the relationships from the schema file rather than the SQL foreign keys?

**Comment by keonik** [comment]
It's probably possible. I'm a little swamped with a newborn currently. If you anyone wants to work on this I'd be happy to review a PR!

**Comment by janpio** [comment]
What does your schema look like @aladinflux? Generally the syntax is not _that_ different, so I would be surprised if the ERD generation would fail because it being for a MongoDB database.

Can you share your Prisma schema here?

**Comment by janpio** [comment]
Ok, I looked into this a bit and found the problem.

This is a standard Prisma schema for MongoDB:

```
model Product {
    id    String @id @map("_id")
    name  String
    foo   Foo    @relation(fields: [fooId], references: [id])
    fooId String
}

model Foo {
    id      String    @id @map("_id")
    bar     String
    Product Product[]
}
```

And this is what Mermaid can render as table columns:
```
The type and name values must begin with an alphabetic character and may contain digits, hyphens or underscores. Other than that, there are no restrictions, and there is no implicit set of valid data types.
```

Note how all the `@id` values are really `_id` in the database? Mermaid does not like that unfortunately.

Not sure what the best way forward here is. If they allowed any other characters we could do `id_(_id)` so also signify the `@map` value, but `()` is of course also not valid :(

Suggestions?

**Comment by janpio** [comment]
For now I added a `z` in front of `_id` to make `z_id` which makes the field name valid.

**Comment by aladinflux** [comment]
I think that I should open a ticket in Mermaid to see if they can work on allowing names starting with underscore

**Comment by janpio** [comment]
That would be of course the _perfect_ solution. Probably not easy for them because of the grammar of the language (same problem that made Prisma also only support field names starting with alphanumeric characters and introduce `@map`)

**Comment by keonik** [comment]
@janpio @aladinflux version `0.10.0` is up

**Comment by keonik** [comment]
Probably should have left that in pre-release. I'm getting some errors on a postgres schema for dbName null values

**Comment by janpio** [comment]
Ohoh. Sorry. Seems we need more tests then :/

**Comment by keonik** [comment]
All good! I'll make a new issue. Are things good on your end?
