### ISSUE TITLE
Could not parse datamodel

### ISSUE THREAD

**Issue by HeinKoZin** [keonik/prisma-erd-generator#66]
Error: could not parse datamodel
    at Object.exports.default [as onGenerate] (D:\My Projects\Nestjs\crud-test\node_modules\prisma-erd-generator\dist\generate.js:175:19)

"prisma-erd-generator": "^0.9.2",

**Comment by keonik** [comment]
@HeinKoZin could you share your schema, OS, and Node version.

**Comment by HeinKoZin** [comment]
Hi, it is fixed by upgrading node version. Thanks.

**Comment by HeinKoZin** [comment]
I still got the same error.
`// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}


generator erd {
  provider = "prisma-erd-generator"
}


model Movie {
  id          Int @id @default(autoincrement())
  imdb_id     String
  title       String
  description String
  watched     Boolean @default(false)
  genre       MoviesOnGenres[]
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
} 

model Genre {
  id          Int @id @default(autoincrement())
  name        String
  movies      MoviesOnGenres[]
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

model MoviesOnGenres {
  movie_id    Int
  genre_id    Int
  movie       Movie @relation(fields: [movie_id], references: [id])
  genre       Genre @relation(fields: [genre_id], references: [id])
  assignedAt  DateTime @default(now())
  assignedBy  String


  @@id([movie_id, genre_id])
}

model User {
  id          Int @id @default(autoincrement())
  name        String
  email       String
  password    String
  role        Role @default(USER)
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

enum Role {
  ADMIN
  USER
}`

**Comment by keonik** [comment]
I'm going to push out an branch with your schema to see what the disconnect is

**Comment by keonik** [comment]
@HeinKoZin The schema you have in this issue has been added to the test suite. It passed on windows, mac, and linux testing for node versions 12,14, and 16. My best guess here is just having an older version of prisma. I believe I'm going to require the latest version of prisma in the next release just to ensure composite types don't cause issues similar to this issue you are seeing.
