### ISSUE TITLE
Nullable or not on generated erd

### ISSUE THREAD

**Issue by orendaeko** [keonik/prisma-erd-generator#83]
Hi there,

thanks for this useful tool, just need to know can we see the required or can nullable at every field on ERD after generated?

**Comment by keonik** [comment]
As of now, I don't think it shows that. It should though! Good find.

**Comment by orendaeko** [comment]
noted thanks for ur attention, hopefully can enjoy this feature

**Comment by keonik** [comment]
So I tried to work on this today... No luck yet. Would love some ideas.

I was trying to add a symbol to the mermaid syntax that would signify required or nullable that would not cause issues with the cli generation step. So far I tried `*`, `?`, `!`, `^` and they all fail to generate. Any other ideas?

**Comment by keonik** [comment]
Found a way to do it. Don't love it but I think its the only way forward. PR incoming

**Comment by keonik** [comment]
and by PR I mean... I pushed to main 🤦🏼‍♂️ release incoming

**Comment by keonik** [comment]
released in `0.11.4`
