### ISSUE TITLE
braintree/sanitize-url audit issue

### ISSUE THREAD

**Issue by alec-pirillo-le** [keonik/prisma-erd-generator#97]
Mermaid relies on braintree/sanitize-url, which has a security issue that was patched in 6.0.0. This dependency was fixed in mermaid >9.0.0, however  prisma-erd-generator still reference an older 8.14.0 version. Can we get a new release with updated dependencies?

**Comment by alec-pirillo-le** [comment]
@keonik It would still be great if this package was updated to depend on mermaid 9.0.0 so people don't need to manually fix.

**Comment by keonik** [comment]
It should be dependent on that in the release. I’ll check again today. 

https://github.com/keonik/prisma-erd-generator/blob/c792db771fa343fcbc623bff531770d9c179fe7b/package.json#L74
