### ISSUE TITLE
Generating files that don't render

### ISSUE THREAD

**Issue by sschun123** [keonik/prisma-erd-generator#98]
I'm able to successfully generate files of the different extensions but they all seem to be empty/not working.

I unfortunately cannot provide my full schema file as it is work related but if I need to then I can obfuscate the names.

```
project
|__ prisma
|____schema.prisma
|____ERD.svg
```

```
generator erd {
	provider = "node node_modules/prisma-erd-generator"
	output = "./ERD.svg"
}
... My prisma models
```

- I have no reason to believe my models are improperly defined since prisma has been working as intended
- My file structure seems in line with what this package expects (see above).
- I have mermaid-js/mermaid-cli and prisma-erd-generator in my package.json and installed.

Here are my output files

ERD.svg
![ERD](https://user-images.githubusercontent.com/40184557/169558444-8fe0e008-5ce0-4798-9354-d1a69ed1b4da.svg)

ERD.png
![ERD](https://user-images.githubusercontent.com/40184557/169558453-8384b1c1-1ab0-4d07-93dc-d59bb9c60ed9.png)

ERD.md did include my models but using mermaid markdown preview in vscode doesn't show anything
```
```mermaid
erDiagram

...my models```
```

**Comment by keonik** [comment]
My first suggestion will be to enable debug mode which will show you what it is generating along the way. In almost all these cases thus far it has been a new edge case we need to add a fix for. 

The only thing I see out of the ordinary above would be the provider link. Is there a reason you're running node and pointing to the library in your node_modules?

Here is what I'm used to seeing

```prisma
generator erd {
  provider = "prisma-erd-generator"
}
```
