### ISSUE TITLE
Not generating ER Diagram

### ISSUE THREAD

**Issue by EuSouVoce** [keonik/prisma-erd-generator#99]
### Already tried:

- ``npm i -D @mermaid-js/mermaid-cli``
- ``npm i -D prisma-erd-generator@latest``
- triple check the schema.prisma

``Error: Issue generating ER Diagram. Expected ~\ERD.svg to be created
    at exports.default [as onGenerate] (~\node_modules\prisma-erd-generator\dist\generate.js:269:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LineStream.<anonymous> (~\node_modules\@prisma\generator-helper\dist\generatorHandler.js:36:24)``

**Any ideas?**

**Comment by keonik** [comment]
No ideas yet. That error is hit when the final file is missing. It could fail at many points before that. 

My first suggestion will be to enable debug mode which will show you what it is generating along the way. In almost all these cases thus far it has been a new edge case we need to add a fix for.

```bash
# .env file
ERD_DEBUG=true
```

**Comment by EuSouVoce** [comment]
https://pastebin.com/JePdKFHc
hi, i've pasted the console output here

**Comment by keonik** [comment]
```mermaid
erDiagram
 
  User {
    String id
    String nickname
    String nome
    String email
    String senha
    String discord
    String java_uuid
    String bedrock_uuid
    DateTime criadoEm
    DateTime editadoEm
    }
 
 
  Post {
    Int id
    String titulo
    String descricao
    DateTime criadoEm
    DateTime editadoEm
    }
 
 
  Comentarios {
    Int id
    String comentario
    DateTime criadoEm
    DateTime editadoEm
    }
 
 
  Categorias {
    Int id
    }
 
 
  Categoria {
    Int id
    String nome
    Int relevancia
    }
 
 
  Cargos {
    Int id
    String nome
    String descricao
    DateTime desde
    DateTime ate
    }
 
 
  Cargo {
    String id
    }
 
    Post o{--|| User : "autor"
    Comentarios o{--|| Post : "Post"
    Comentarios o{--|| User : "autor"
    Categorias o{--|| Post : "Posts"
    Categorias o{--|| Categoria : "Categoria"
    Cargos o{--|| User : "User"
    Cargos o{--|| Cargo : "cargo"
 
```

**Comment by keonik** [comment]
Looks like everything is good in the mermaid syntax. Next would be to figure out where it could fail in the CLI

**Comment by keonik** [comment]
@EuSouVoce Any chance to try out the debug mode and get some more validation? As a fallback you can just use the markdown output and it will generate the ER above
